**Quiz 4**

In [ ]:
# (1)
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzz(x):
    answer =""
    if x %3==0 and not x%5==0:
      answer="Fizz!"
    elif x%5==0 and not x%3==0:
      answer="Buzz!"
    elif x%3 ==0 and x%5==0:
      answer="FizzBuzz!"
    else:
      answer="..."
    return answer


In [ ]:
print(FizzBuzz(3))
print(FizzBuzz(7))
print(FizzBuzz(5))
print(FizzBuzz(11))
print(FizzBuzz(15))

Fizz!
...
Buzz!
...
FizzBuzz!


Expected output:
``` 
Fizz!
...
Buzz!
...
FizzBuzz!
```

In [ ]:
# (1)
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzzList(n):
    ans = []
    for i in range(1,n+1):
        ans.append(FizzBuzz(i))
    return ans

In [ ]:
print(FizzBuzzList(5))
print(FizzBuzzList(-30))

['...', '...', 'Fizz!', '...', 'Buzz!']
[]


Expected output:
``` 
['...', '...', 'Fizz!', '...', 'Buzz!']
[]
```

In [ ]:
# (3)
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def standarize(X):
  X_standarized = (X-X.mean())/X.std()# only one line of code
  return X_standarized

In [ ]:
# run this sample testcases to help you validate your solution

X0 = np.array([4.8, 4.0, 4.2, 4.0, 5.0])
print(standarize(X0))

#  --> Expected output: array([ 0.95346259, -0.95346259, -0.47673129, -0.95346259,  1.43019388])

X1 = np.arange(5)
print(standarize(X1))

#  --> Expected output: array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

[ 0.95346259 -0.95346259 -0.47673129 -0.95346259  1.43019388]


array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [ ]:
# (4)
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def main_diagonal_matrix(A):
  D = np.diag(np.diag(A)).astype(float)# only one line of code
  return D

In [ ]:
# run this sample testcases to help you validate your solution

A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]

])
print(main_diagonal_matrix(A))
#  --> Expected output: 
#array([[1., 0., 0.],
#       [0., 2., 0.],
#       [0., 0., 3.]])

A = np.array([
    [4, 0, 2],
    [9, 5, 6],
    [1, 9, 6],
    [3, 0, 5]

])
print(main_diagonal_matrix(A))
#  --> Expected output: 
#array([[4., 0., 0.],
#       [0., 5., 0.],
#       [0., 0., 6.]])

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[[4. 0. 0.]
 [0. 5. 0.]
 [0. 0. 6.]]
